config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :products_apis

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    validates :product_name, uniqueness: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_apis_controller.rb
class ProductsApisController < ApplicationController
    before_action :set_product, only: %i[ show edit update destroy ]
  
    # GET /products_apis or /products_apis.json
    def index
      @products_apis = Product.all
      render json: @products_apis
    end
  
    # GET /products_apis/1 or /products_apis/1.json
    def show
      @products_api = @products_apis.find(params[:id])
  
      render json: @products_api
    end
    
    # GET /products_apis/new
    def new
      @products_api = Product.new
    end
  
    # GET /products_apis/1/edit
    def edit
    end
  
    # POST /products_apis or /products_apis.json
    def create
      @products_api = Product.new(product_params)
    end
  
    # PATCH/PUT /products_apis/1 or /products_apis/1.json
    def update
    end
  
    # DELETE /products_apis/1 or /products_apis/1.json
    def destroy
      @products_api.destroy
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_product
        @products_api = Product.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def product_params
        params.require(:product).permit(:product_name, :product_image, :product_description, :product_price, :product_bg_color)
      end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GSneaker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/products_apis/_form.html.erb
<%= form_with(model: products_api) do |form| %>
  <% if products_api.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(products_api.errors.count, "error") %> prohibited this products_api from being saved:</h2>

      <ul>
        <% products_api.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/products_apis/_products_api.html.erb
<div id="<%= dom_id products_api %>">
</div>

app/views/layouts/products_apis/edit.html.erb
<h1>Editing products api</h1>

<%= render "form", products_api: @products_api %>

<br>

<div>
  <%= link_to "Show this products api", @products_api %> |
  <%= link_to "Back to products apis", products_apis_path %>
</div>

app/views/layouts/products_apis/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>products apis</h1>

<div id="products_apis">
  <% @products_apis.each do |products_api| %>
    <%= render products_api %>
    <p>
      <%= link_to "Show this products api", products_api %>
    </p>
  <% end %>
</div>

<%= link_to "New products api", new_products_api_path %>

app/views/layouts/products_apis/new.html.erb
<h1>New products api</h1>

<%= render "form", products_api: @products_api %>

<br>

<div>
  <%= link_to "Back to products apis", products_apis_path %>
</div>

app/views/layouts/products_apis/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @products_api %>

<div>
  <%= link_to "Edit this products api", edit_products_api_path(@products_api) %> |
  <%= link_to "Back to products apis", products_apis_path %>

  <%= button_to "Destroy this products api", @products_api, method: :delete %>
</div>